import {test} from 'node:test';
import assert from 'node:assert/strict';
import {applyAction,emptyCounts,aggregate,probabilities,publicGame} from '../lib/game.ts';
import fs from 'node:fs';
const fixture=(prize=0)=>({session:{...emptyCounts,id:'test',name:'Test',pointsForWin:10,pointsForLoss:5,startingPoints:100,finalPoints:100,status:'active',source:'live'},round:{prize,picked:null,opened:null,phase:'pick'},version:0,lastMutationId:''});
test('host never opens selected or prize door; switch wins exactly 2/3 of exhaustive placements',()=>{let stayWins=0,switchWins=0;for(let prize=0;prize<3;prize++)for(let pick=0;pick<3;pick++){const chosen=applyAction(fixture(prize),'choose',pick);assert.notEqual(chosen.round.opened,pick);assert.notEqual(chosen.round.opened,prize);assert.equal(publicGame(chosen).round.prize,undefined);const stay=applyAction(chosen,'stay'),switched=applyAction(chosen,'switch');stayWins+=Number(stay.round.won);switchWins+=Number(switched.round.won);assert.equal(stay.session.finalPoints,stay.round.won?110:95);assert.equal(switched.session.finalPoints,switched.round.won?110:95);assert.throws(()=>applyAction(stay,'stay'));}assert.equal(stayWins,3);assert.equal(switchWins,6)});
test('unfinished rounds do not count; ended sessions reject new actions',()=>{const ended=applyAction(applyAction(fixture(),'choose',0),'end');assert.deepEqual(aggregate([ended.session]),emptyCounts);assert.equal(ended.session.finalPoints,100);assert.throws(()=>applyAction(ended,'switch'))});
test('empty probabilities are undefined, not misleading zeroes',()=>{assert.ok(Object.values(probabilities(emptyCounts)).every(v=>v===null));assert.throws(()=>applyAction(fixture(),'choose',3));assert.throws(()=>applyAction(fixture(),'choose',-1))});
test('historical records exactly reproduce 464 trials and all final banks',()=>{const {sessions}=JSON.parse(fs.readFileSync(new URL('../public/sessions.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));assert.equal(sessions.length,25);assert.deepEqual(aggregate(sessions),{stayLoss:127,stayWin:81,switchLoss:93,switchWin:163});for(const s of sessions)assert.equal(s.startingPoints+(s.stayWin+s.switchWin)*s.pointsForWin-(s.stayLoss+s.switchLoss)*s.pointsForLoss,s.finalPoints);assert.equal(sessions[0].startingPoints,-10);const p=probabilities(aggregate(sessions));assert.equal(p.winGivenStay,81/208);assert.equal(p.winGivenSwitch,163/256);assert.equal(p.win,244/464)});
