CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  points_for_win INTEGER NOT NULL CHECK (points_for_win >= 0),
  points_for_loss INTEGER NOT NULL CHECK (points_for_loss >= 0),
  starting_points INTEGER NOT NULL,
  final_points INTEGER NOT NULL,
  stay_loss INTEGER NOT NULL DEFAULT 0 CHECK (stay_loss >= 0),
  stay_win INTEGER NOT NULL DEFAULT 0 CHECK (stay_win >= 0),
  switch_loss INTEGER NOT NULL DEFAULT 0 CHECK (switch_loss >= 0),
  switch_win INTEGER NOT NULL DEFAULT 0 CHECK (switch_win >= 0),
  status TEXT NOT NULL CHECK (status IN ('active', 'ended')),
  source TEXT NOT NULL CHECK (source IN ('live', 'historical')),
  starting_points_source TEXT,
  created_at TEXT,
  ended_at TEXT,
  token_hash TEXT,
  version INTEGER NOT NULL DEFAULT 0,
  last_mutation_id TEXT,
  round_prize INTEGER CHECK (round_prize BETWEEN 0 AND 2),
  round_picked INTEGER CHECK (round_picked BETWEEN 0 AND 2),
  round_opened INTEGER CHECK (round_opened BETWEEN 0 AND 2),
  round_phase TEXT CHECK (round_phase IN ('pick', 'decide', 'reveal')),
  round_decision TEXT CHECK (round_decision IN ('stay', 'switch')),
  round_final_door INTEGER CHECK (round_final_door BETWEEN 0 AND 2),
  round_won INTEGER CHECK (round_won IN (0, 1)),
  CHECK (final_points = starting_points + (stay_win + switch_win) * points_for_win - (stay_loss + switch_loss) * points_for_loss)
);
