import type {Game,Session,Round} from '../lib/game';
export type Row=Record<string,string|number|null>;
const sessionColumns={id:'id',name:'name',pointsForWin:'points_for_win',pointsForLoss:'points_for_loss',startingPoints:'starting_points',finalPoints:'final_points',stayLoss:'stay_loss',stayWin:'stay_win',switchLoss:'switch_loss',switchWin:'switch_win',status:'status',source:'source',startingPointsSource:'starting_points_source',createdAt:'created_at',endedAt:'ended_at'} as const;
export function sessionFromRow(row:Row):Session{const s:Record<string,unknown>={};for(const [key,column] of Object.entries(sessionColumns)){if(row[column]!==null)s[key]=row[column]}return s as Session}
export function gameFromRow(row:Row):Game{return {session:sessionFromRow(row),version:Number(row.version),lastMutationId:String(row.last_mutation_id||''),round:{prize:Number(row.round_prize),picked:row.round_picked===null?null:Number(row.round_picked),opened:row.round_opened===null?null:Number(row.round_opened),phase:row.round_phase as Round['phase'],...(row.round_decision?{decision:row.round_decision as 'stay'|'switch'}:{}),...(row.round_final_door!==null?{finalDoor:Number(row.round_final_door)}:{}),...(row.round_won!==null?{won:row.round_won===1}:{})}}}
export function rowFromGame(game:Game,tokenHash:string):Row{const s=game.session,r=game.round,row:Row={};for(const [key,column] of Object.entries(sessionColumns))row[column]=s[key as keyof Session]??null;return {...row,token_hash:tokenHash,version:game.version,last_mutation_id:game.lastMutationId,round_prize:r.prize,round_picked:r.picked,round_opened:r.opened,round_phase:r.phase,round_decision:r.decision??null,round_final_door:r.finalDoor??null,round_won:r.won===undefined?null:Number(r.won)}}
export async function insertGame(db:D1Database,game:Game,tokenHash:string){const row=rowFromGame(game,tokenHash),columns=Object.keys(row);return db.prepare(`INSERT OR IGNORE INTO sessions (${columns.join(',')}) VALUES (${columns.map(()=>'?').join(',')})`).bind(...Object.values(row)).run()}
export async function updateGame(db:D1Database,game:Game,tokenHash:string,expectedVersion:number){const row=rowFromGame(game,tokenHash);delete row.id;return db.prepare(`UPDATE sessions SET ${Object.keys(row).map(column=>column+' = ?').join(', ')} WHERE id = ? AND version = ?`).bind(...Object.values(row),game.session.id,expectedVersion).run()}
export async function findSession(db:D1Database,id:string){return db.prepare('SELECT * FROM sessions WHERE id = ?').bind(id).first<Row>()}
export async function listSessions(db:D1Database){const rows=await db.prepare('SELECT id, name, points_for_win, points_for_loss, starting_points, final_points, stay_loss, stay_win, switch_loss, switch_win, status, source, starting_points_source, created_at, ended_at FROM sessions ORDER BY name COLLATE NOCASE DESC, id DESC').all<Row>();return rows.results.map(sessionFromRow)}
